//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDDT_CTNS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttnsvsmttvhservicedemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string HDDT_CTNS_plWebservice_PublishService {
            get {
                return ((string)(this["HDDT_CTNS_plWebservice_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttnsvsmttvhservicedemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string HDDT_CTNS_portalWebsevice_PortalService {
            get {
                return ((string)(this["HDDT_CTNS_portalWebsevice_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttnsvsmttvhservicedemo.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string HDDT_CTNS_bsWebservice_BusinessService {
            get {
                return ((string)(this["HDDT_CTNS_bsWebservice_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8J7FCAC\\SQLEXPRESS;Initial Catalog=TVWater;User ID=NUOCSACH;P" +
            "assword=123@123")]
        public string TVWaterConnectionString {
            get {
                return ((string)(this["TVWaterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8J7FCAC\\SQLEXPRESS;Initial Catalog=TVWater;Integrated Securit" +
            "y=True")]
        public string TVWaterConnectionString1 {
            get {
                return ((string)(this["TVWaterConnectionString1"]));
            }
        }
    }
}
